kind: pipeline
type: docker
name: CI

trigger:
  event:
    - push

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk:9.0
    commands:
      - cd Sources/DouShouQi/
      - dotnet restore DouShouQiWithoutMAUI.sln
      - dotnet build DouShouQiWithoutMAUI.sln -c Release --no-restore
      - dotnet publish DouShouQiWithoutMAUI.sln -c Release --no-restore -o $CI_PROJECT_DIR/build/release

  - name: tests
    image: mcr.microsoft.com/dotnet/sdk:9.0
    commands:
      - cd Sources/DouShouQi/
      - dotnet restore DouShouQiWithoutMAUI.sln
      - dotnet test DouShouQiWithoutMAUI.sln --no-restore
    depends_on: [build]

  - name: code-inspection
    image: hub.codefirst.iut.uca.fr/marc.chevaldonne/codefirst-dronesonarplugin-dotnet9
    secrets: [ SECRET_SONAR_LOGIN ]
    environment:
      sonar_host: https://codefirst.iut.uca.fr/sonar/
      sonar_token:
        from_secret: sonar_token
      project_key: sonar_token_DouShouQi
      coverage_exclusions: "Tests/**"
    depends_on: [build]
    commands:
      - cd Sources/DouShouQi/
      - dotnet restore DouShouQiWithoutMAUI.sln
      - dotnet sonarscanner begin /k:$${project_key} /d:sonar.host.url=$${sonar_host} /d:sonar.coverageReportPaths="coveragereport/SonarQube.xml" /d:sonar.coverage.exclusions=$${coverage_exclusions} /d:sonar.login=$${sonar_token} 
      - dotnet build DouShouQiWithoutMAUI.sln -c Release --no-restore
      - dotnet test DouShouQiWithoutMAUI.sln --logger trx --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura --collect "XPlat Code Coverage"
      - reportgenerator -reports:"**/coverage.cobertura.xml" -reporttypes:SonarQube -targetdir:"coveragereport"
      - dotnet publish DouShouQiWithoutMAUI.sln -c Release --no-restore -o CI_PROJECT_DIR/build/release
      - dotnet sonarscanner end /d:sonar.login=$${sonar_token}

  - name: generate-and-deploy-docs
    image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-docdeployer
    failure: ignore
    volumes:
      - name: docs
        path: /docs
    commands:
      - /entrypoint.sh
    when:
      branch:
        - master
